workflow changes

diff --git a/.github/workflows/test-vineflower.yml b/.github/workflows/test-vineflower.yml
--- a/.github/workflows/test-vineflower.yml
+++ b/.github/workflows/test-vineflower.yml
@@ -12,12 +12,6 @@ jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-      - name: Set up JDK
-        uses: actions/setup-java@v3
-        with:
-          distribution: 'temurin'
-          java-version: '17'
-
       - name: Checkout repository
         uses: actions/checkout@v3
         with:
@@ -30,12 +24,18 @@ jobs:
           ref: ${{ github.event.inputs.vf_branch }}
           path: vineflower
 
+      - name: Set up JDK
+        uses: actions/setup-java@v3
+        with:
+          distribution: 'temurin'
+          java-version: '17'
+          cache: 'gradle'
+
       - name: Build Vineflower
         run: |
           cd vineflower
           # Setting the STATUS is used to easily identify the build from multiple output jars
           STATUS=snapshot ./gradlew publishtomavenlocal -x test
-          cd ..
 
       - name: Decompile Minecraft
         run: |
@@ -43,6 +43,25 @@ jobs:
           ./gradlew applyPatches
 
       - name: Try to build
+        continue-on-error: true
         run: |
           cd mache
-          ./gradlew build
+          ( ./gradlew build 3>&1 1>&2- 2>&3- ) | tee build-log.txt
+
+      - uses: actions/upload-artifact@v3
+        with:
+          name: build-log
+          path: mache/build-log.txt
+
+      - uses: actions/upload-artifact@v3
+        with:
+          name: decompile-log
+          path: mache/versions/*/build/mache/input/decomp.jar.log
+
+      - run: |
+          cd mache
+          regex="([0-9]+) errors"
+          if [[ $(cat build-log.txt) =~ $regex ]] then
+            echo "# Re-compile errors" >> $GITHUB_STEP_SUMMARY
+            echo "${BASH_REMATCH[1]} errors found" >> $GITHUB_STEP_SUMMARY
+          fi
